create table noteful_notes (
    id integer primary key generated by default as identity,
    name text not null,
    content text not null,
    folder_id integer
        references noteful_folders(id) on delete cascade not null
);